export const dummyUserData = {
  user: {
    name: "Sarah Johnson",
    profilePic: "/placeholder.svg?height=128&width=128",
    email: "sarah.johnson@example.com",
    bio: "Passionate learner and technology enthusiast. I love exploring new programming languages and building innovative solutions. Currently focusing on full-stack development and machine learning.",
    location: "San Francisco, CA",
    joinDate: "January 2023",
    phone: "+1 (555) 123-4567",
    enrolledCourses: 12,
    completedCourses: 8,
    certificates: 5,
  },
  courses: [
    {
      id: "1",
      title: "React Advanced Patterns",
      description: "Master advanced React patterns including hooks, context, and performance optimization techniques.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      price: 99,
      duration: "8 hours",
      level: "Advanced",
      creator: "John Doe",
      progress: 75,
    },
    {
      id: "2",
      title: "Node.js Backend Development",
      description: "Build scalable backend applications with Node.js, Express, and MongoDB.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      price: 79,
      duration: "12 hours",
      level: "Intermediate",
      creator: "Jane Smith",
      progress: 45,
    },
    {
      id: "3",
      title: "JavaScript Fundamentals",
      description: "Learn the core concepts of JavaScript programming from scratch.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      price: 49,
      duration: "6 hours",
      level: "Beginner",
      creator: "Mike Wilson",
      progress: 100,
    },
    {
      id: "4",
      title: "Python Data Science",
      description: "Analyze data and build machine learning models using Python libraries.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      price: 129,
      duration: "15 hours",
      level: "Intermediate",
      creator: "Dr. Emily Chen",
      progress: 30,
    },
    {
      id: "5",
      title: "UI/UX Design Principles",
      description: "Create beautiful and user-friendly interfaces with modern design principles.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      price: 89,
      duration: "10 hours",
      level: "Beginner",
      creator: "Alex Rodriguez",
      progress: 60,
    },
    {
      id: "6",
      title: "DevOps with Docker",
      description: "Learn containerization and deployment strategies using Docker and Kubernetes.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      price: 109,
      duration: "14 hours",
      level: "Advanced",
      creator: "Sarah Kim",
      progress: 20,
    },
  ],
  certificates: [
    {
      id: "1",
      title: "React Developer Certification",
      description: "Certified in advanced React development patterns and best practices.",
      issuedBy: "Tech Academy",
      issuedDate: "2024-03-15",
      badge: "react-cert",
    },
    {
      id: "2",
      title: "JavaScript Expert",
      description: "Demonstrated expertise in modern JavaScript development and ES6+ features.",
      issuedBy: "Code Institute",
      issuedDate: "2024-02-20",
      badge: "js-expert",
    },
    {
      id: "3",
      title: "Full Stack Developer",
      description: "Completed comprehensive full-stack development program covering frontend and backend technologies.",
      issuedBy: "Dev Bootcamp",
      issuedDate: "2024-01-10",
      badge: "fullstack-cert",
    },
    {
      id: "4",
      title: "UI/UX Design Specialist",
      description: "Certified in user interface and user experience design principles and methodologies.",
      issuedBy: "Design Academy",
      issuedDate: "2023-12-05",
      badge: "design-cert",
    },
    {
      id: "5",
      title: "Python Data Analyst",
      description: "Proficient in data analysis and visualization using Python and related libraries.",
      issuedBy: "Data Science Institute",
      issuedDate: "2023-11-18",
      badge: "python-data",
    },
  ],
  quizzes: [
    {
      id: "1",
      title: "React Hooks Mastery",
      description: "Test your knowledge of React hooks including useState, useEffect, and custom hooks.",
      score: 92,
      completionDate: "2024-03-20",
      totalQuestions: 25,
    },
    {
      id: "2",
      title: "JavaScript ES6+ Features",
      description: "Comprehensive quiz covering modern JavaScript features and syntax.",
      score: 88,
      completionDate: "2024-03-18",
      totalQuestions: 30,
    },
    {
      id: "3",
      title: "Node.js Fundamentals",
      description: "Basic concepts of Node.js runtime and server-side JavaScript development.",
      score: 76,
      completionDate: "2024-03-15",
      totalQuestions: 20,
    },
    {
      id: "4",
      title: "CSS Grid and Flexbox",
      description: "Modern CSS layout techniques for responsive web design.",
      score: 94,
      completionDate: "2024-03-12",
      totalQuestions: 18,
    },
    {
      id: "5",
      title: "Database Design Principles",
      description: "Relational database design, normalization, and SQL query optimization.",
      score: 82,
      completionDate: "2024-03-10",
      totalQuestions: 22,
    },
    {
      id: "6",
      title: "Web Security Basics",
      description: "Common web vulnerabilities and security best practices for developers.",
      score: 67,
      completionDate: "2024-03-08",
      totalQuestions: 15,
    },
  ],
}
