export const dummyCourses = [
  {
    id: "1",
    title: "React Fundamentals",
    description:
      "Learn the basics of React including components, props, state, and hooks. This comprehensive course will take you from beginner to intermediate level with hands-on projects and real-world examples.",
    thumbnail: "/placeholder.svg?height=200&width=400",
    level: "Beginner",
    duration: "8 hours",
    createdAt: "2024-01-15",
    lessons: [
      {
        id: "1",
        course_id: "1",
        title: "Introduction to React",
        content: "react-intro-content.pdf",
        video_url: "https://youtube.com/watch?v=example1",
        order: 1,
        isCompleted: true,
        createdAt: "2024-01-15",
      },
      {
        id: "2",
        course_id: "1",
        title: "Components and JSX",
        content: "components-jsx-content.pdf",
        video_url: "https://youtube.com/watch?v=example2",
        order: 2,
        isCompleted: true,
        createdAt: "2024-01-16",
      },
      {
        id: "3",
        course_id: "1",
        title: "Props and State",
        content: "props-state-content.pdf",
        video_url: "",
        order: 3,
        isCompleted: false,
        createdAt: "2024-01-17",
      },
      {
        id: "4",
        course_id: "1",
        title: "React Hooks",
        content: "",
        video_url: "https://youtube.com/watch?v=example4",
        order: 4,
        isCompleted: false,
        createdAt: "2024-01-18",
      },
    ],
    quizzes: [
      {
        id: "1",
        title: "React Basics Quiz",
        description: "Test your knowledge of React fundamentals",
        duration: "15 min",
        questions: [
          {
            id: "1",
            question: "What is React?",
            options: ["A database", "A JavaScript library", "A CSS framework", "A server"],
            correctAnswer: 1,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    title: "Advanced JavaScript",
    description:
      "Deep dive into advanced JavaScript concepts including closures, prototypes, async programming, and modern ES6+ features. Perfect for developers looking to master JavaScript.",
    thumbnail: "/placeholder.svg?height=200&width=400",
    level: "Advanced",
    duration: "12 hours",
    createdAt: "2024-01-10",
    lessons: [
      {
        id: "5",
        course_id: "2",
        title: "Closures and Scope",
        content: "closures-scope-content.pdf",
        video_url: "https://youtube.com/watch?v=example5",
        order: 1,
        isCompleted: false,
        createdAt: "2024-01-10",
      },
      {
        id: "6",
        course_id: "2",
        title: "Prototypes and Inheritance",
        content: "prototypes-inheritance-content.pdf",
        video_url: "",
        order: 2,
        isCompleted: false,
        createdAt: "2024-01-11",
      },
      {
        id: "7",
        course_id: "2",
        title: "Async Programming",
        content: "",
        video_url: "https://youtube.com/watch?v=example7",
        order: 3,
        isCompleted: false,
        createdAt: "2024-01-12",
      },
    ],
    quizzes: [
      {
        id: "2",
        title: "Advanced JS Concepts",
        description: "Test your understanding of advanced JavaScript",
        duration: "20 min",
        questions: [],
      },
    ],
  },
  {
    id: "3",
    title: "Node.js Backend Development",
    description:
      "Build scalable backend applications with Node.js, Express, and MongoDB. Learn about REST APIs, authentication, middleware, and deployment strategies.",
    thumbnail: "/placeholder.svg?height=200&width=400",
    level: "Intermediate",
    duration: "15 hours",
    createdAt: "2024-01-05",
    lessons: [
      {
        id: "8",
        course_id: "3",
        title: "Node.js Fundamentals",
        content: "nodejs-fundamentals-content.pdf",
        video_url: "https://youtube.com/watch?v=example8",
        order: 1,
        isCompleted: false,
        createdAt: "2024-01-05",
      },
      {
        id: "9",
        course_id: "3",
        title: "Express.js Framework",
        content: "express-framework-content.pdf",
        video_url: "https://youtube.com/watch?v=example9",
        order: 2,
        isCompleted: false,
        createdAt: "2024-01-06",
      },
    ],
    quizzes: [],
  },
  {
    id: "4",
    title: "Python for Data Science",
    description:
      "Master Python programming for data analysis, visualization, and machine learning. Includes NumPy, Pandas, Matplotlib, and Scikit-learn.",
    thumbnail: "/placeholder.svg?height=200&width=400",
    level: "Intermediate",
    duration: "20 hours",
    createdAt: "2024-01-01",
    lessons: [
      {
        id: "10",
        course_id: "4",
        title: "Python Basics for Data Science",
        content: "python-basics-data-science.pdf",
        video_url: "",
        order: 1,
        isCompleted: true,
        createdAt: "2024-01-01",
      },
      {
        id: "11",
        course_id: "4",
        title: "NumPy and Arrays",
        content: "numpy-arrays-content.pdf",
        video_url: "https://youtube.com/watch?v=example11",
        order: 2,
        isCompleted: true,
        createdAt: "2024-01-02",
      },
      {
        id: "12",
        course_id: "4",
        title: "Pandas for Data Manipulation",
        content: "",
        video_url: "https://youtube.com/watch?v=example12",
        order: 3,
        isCompleted: false,
        createdAt: "2024-01-03",
      },
    ],
    quizzes: [
      {
        id: "3",
        title: "Python Data Science Quiz",
        description: "Test your Python data science knowledge",
        duration: "25 min",
        questions: [],
      },
    ],
  },
  {
    id: "5",
    title: "UI/UX Design Principles",
    description:
      "Learn the fundamentals of user interface and user experience design. Cover design thinking, wireframing, prototyping, and usability testing.",
    thumbnail: "/placeholder.svg?height=200&width=400",
    level: "Beginner",
    duration: "10 hours",
    createdAt: "2023-12-20",
    lessons: [
      {
        id: "13",
        course_id: "5",
        title: "Design Thinking Process",
        content: "design-thinking-process.pdf",
        video_url: "https://youtube.com/watch?v=example13",
        order: 1,
        isCompleted: false,
        createdAt: "2023-12-20",
      },
      {
        id: "14",
        course_id: "5",
        title: "User Research Methods",
        content: "user-research-methods.pdf",
        video_url: "",
        order: 2,
        isCompleted: false,
        createdAt: "2023-12-21",
      },
    ],
    quizzes: [],
  },
  {
    id: "6",
    title: "DevOps and Cloud Computing",
    description:
      "Master modern DevOps practices and cloud technologies. Learn Docker, Kubernetes, CI/CD pipelines, and cloud deployment strategies.",
    thumbnail: "/placeholder.svg?height=200&width=400",
    level: "Advanced",
    duration: "18 hours",
    createdAt: "2023-12-15",
    lessons: [],
    quizzes: [],
  },
]
